/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class B11 */

#ifndef _Included_B11
#define _Included_B11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     B11
 * Method:    add1
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_B11_add1
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     B11
 * Method:    sub1
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_B11_sub1
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     B11
 * Method:    multi
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_B11_multi
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     B11
 * Method:    divi
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_B11_divi
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
